In [21]:
import pandas as pd
import numpy as np

In [34]:
from sklearn.preprocessing import LabelEncoder

In [50]:
from sklearn.model_selection import train_test_split

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [22]:
df = pd.read_csv("artifacts/raw_dataset.csv")

In [23]:
df.shape

(303, 15)

In [24]:
df.columns

Index(['Unnamed: 0', 'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [25]:
df = df.drop(df.columns[0], axis=1)

In [26]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,male,3,145.0,233.0,1,0,150.0,0,2.3,0,0,1,yes
1,37,male,2,130.0,250.0,0,1,187.0,0,3.5,0,0,2,yes
2,41,female,1,130.0,204.0,0,0,172.0,0,1.4,2,0,2,yes
3,56,male,1,120.0,236.0,0,1,178.0,0,0.8,2,0,2,yes
4,57,female,0,NaN,354.0,0,1,163.0,1,0.6,2,0,2,yes

In [27]:
df.describe()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
count,303.000000,303.000000,299.000000,302.000000,303.000000,303.000000,298.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.966997,131.712375,246.317881,0.148515,0.528053,149.865772,0.326733,1.039604,1.399340,0.729373,2.313531
std,9.082101,1.032052,17.629032,51.908285,0.356198,0.525860,22.563687,0.469794,1.161075,0.616226,1.022606,0.612277
min,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,120.000000,211.000000,0.000000,0.000000,134.500000,0.000000,0.000000,1.000000,0.000000,2.000000
50%,55.000000,1.000000,130.000000,240.500000,0.000000,1.000000,152.500000,0.000000,0.800000,1.000000,0.000000,2.000000
75%,61.000000,2.000000,140.000000,274.750000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000
max,77.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000

In [28]:
df.dtypes

age           int64
sex          object
cp            int64
trestbps    float64
chol        float64
fbs           int64
restecg       int64
thalach     float64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target       object
dtype: object

In [29]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    4
chol        1
fbs         0
restecg     0
thalach     5
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [30]:
df = df.dropna()

In [32]:
df = df.drop_duplicates()

In [33]:
df.shape

(292, 14)

In [35]:
label_encoder = LabelEncoder()

In [36]:
df['sex_encoded'] = label_encoder.fit_transform(df['sex'])

In [44]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,sex_encoded
0,63,male,3,145.0,233.0,1,0,150.0,0,2.3,0,0,1,yes,1
1,37,male,2,130.0,250.0,0,1,187.0,0,3.5,0,0,2,yes,1
2,41,female,1,130.0,204.0,0,0,172.0,0,1.4,2,0,2,yes,0
3,56,male,1,120.0,236.0,0,1,178.0,0,0.8,2,0,2,yes,1
5,57,male,0,140.0,192.0,0,1,148.0,0,0.4,1,0,1,yes,1

In [45]:
df.drop(df.columns[1], axis=1, inplace=True)

In [46]:
df.head()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,sex_encoded
0,63,3,145.0,233.0,1,0,150.0,0,2.3,0,0,1,yes,1
1,37,2,130.0,250.0,0,1,187.0,0,3.5,0,0,2,yes,1
2,41,1,130.0,204.0,0,0,172.0,0,1.4,2,0,2,yes,0
3,56,1,120.0,236.0,0,1,178.0,0,0.8,2,0,2,yes,1
5,57,0,140.0,192.0,0,1,148.0,0,0.4,1,0,1,yes,1

In [47]:
df['target_encoded'] = label_encoder.fit_transform(df['target'])

In [48]:
df.drop('target', axis=1, inplace=True)

In [49]:
df.head()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,sex_encoded,target_encoded
0,63,3,145.0,233.0,1,0,150.0,0,2.3,0,0,1,1,1
1,37,2,130.0,250.0,0,1,187.0,0,3.5,0,0,2,1,1
2,41,1,130.0,204.0,0,0,172.0,0,1.4,2,0,2,0,1
3,56,1,120.0,236.0,0,1,178.0,0,0.8,2,0,2,1,1
5,57,0,140.0,192.0,0,1,148.0,0,0.4,1,0,1,1,1

In [51]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.2, random_state=42)

In [52]:
X_train.head()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,sex_encoded
218,65,0,135.0,254.0,0,0,127.0,0,2.8,1,1,3,1
237,60,0,140.0,293.0,0,0,170.0,0,1.2,1,2,3,1
234,70,0,130.0,322.0,0,0,109.0,0,2.4,1,3,2,1
76,51,2,125.0,245.0,1,0,166.0,0,2.4,1,0,2,1
27,51,2,110.0,175.0,0,1,123.0,0,0.6,2,0,2,1

In [53]:
y_train.head()

218    0
237    0
234    0
76     1
27     1
Name: target_encoded, dtype: int32

In [55]:
model = RandomForestClassifier()

In [56]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [57]:
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

Accuracy: 0.864406779661017